# Generated by Django 5.2.17 on 2026-09-27 19:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('github_user_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True)),
                ('allow_private', models.BooleanField(default=False)),
                ('ai_consent', models.BooleanField(default=False)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RateBucket',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window', models.BigIntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('fetching', 'Fetching Repository'), ('inspecting', 'Inspecting Files'), ('analyzing', 'Analyzing'), ('complete', 'Complete'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('commit_sha', models.CharField(blank=True, max_length=64)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('analysis_version', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('available_at', models.DateTimeField()),
                ('lease_until', models.DateTimeField(null=True)),
                ('lease_token', models.UUIDField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('cached', models.BooleanField(default=False)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('evidence', models.JSONField(default=dict)),
                ('changes', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GitHubAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('refresh_expires_at', models.DateTimeField(null=True)),
                ('scopes', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_id', models.BigIntegerField()),
                ('owner', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('private', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('fork', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('pushed_at', models.DateTimeField(null=True)),
                ('latest_commit_sha', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryAnalysis',
            fields=[
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analysis', serialize=False, to='reaper.repositoryscan')),
                ('project_status', models.CharField(db_index=True, max_length=40)),
                ('resurrection_effort', models.CharField(db_index=True, max_length=30)),
                ('portfolio_value', models.CharField(db_index=True, max_length=10)),
                ('result', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='repositoryscan',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='reaper.repository'),
        ),
        migrations.AddField(
            model_name='repositoryscan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ResurrectionQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('Next', 'Next'), ('Soon', 'Soon'), ('Someday', 'Someday')], default='Soon', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='reaper.repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('etag', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='reaper_gith_expires_ffb094_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='cache_user_key_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['user', 'name'], name='reaper_repo_user_id_3c9715_idx'),
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(fields=('user', 'github_id'), name='repo_user_github_unique'),
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(fields=('id', 'user'), name='repo_id_user_unique'),
        ),
        migrations.AddField(
            model_name='repositoryanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='repositoryscan',
            index=models.Index(fields=['status', 'available_at'], name='reaper_repo_status_af4487_idx'),
        ),
        migrations.AddIndex(
            model_name='repositoryscan',
            index=models.Index(fields=['user', 'repository', 'created_at'], name='reaper_repo_user_id_c1b471_idx'),
        ),
        migrations.AddConstraint(
            model_name='repositoryscan',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'fetching', 'inspecting', 'analyzing'])), fields=('user', 'repository'), name='one_active_scan_per_repo'),
        ),
        migrations.AddConstraint(
            model_name='repositoryscan',
            constraint=models.UniqueConstraint(fields=('id', 'user'), name='scan_id_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='resurrectionqueueitem',
            constraint=models.UniqueConstraint(fields=('user', 'repository'), name='queue_user_repo_unique'),
        ),
    ]
