# Generated by Django 5.2.17 on 2026-09-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaper', '0002_tenant_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_epoch',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
