# Generated by Django 5.2.17 on 2026-09-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaper', '0003_user_privacy_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratebucket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
