# Generated by Django 5.2.17 on 2026-09-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaper', '0004_ratebucket_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scan_budget_started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='scan_budget_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
