# Generated by Django 5.2.17 on 2026-09-27 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaper', '0005_user_scan_budget_started_at_user_scan_budget_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('api_key', models.TextField()),
                ('key_hint', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
